spring:
  profiles:
    group:
      dev: profile1
      test: profile2
      prod: profile3

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: profile1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(otcBFAtYYFq/mbA/5xikmIolbO4g5Hp4Uhq2bZb1p4oTC2U0NnwEz44RDMX+Qqrl)
    username: ENC(DctjhSLWDCmyuDSsyI6WFw==)
    password: ENC(DctjhSLWDCmyuDSsyI6WFw==)

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
  packages-to-scan: com.jootcamp.superboard
  swagger-ui:
    display-request-duration: true # 딜레이를 두고 요청하도록 설정
    operations-sorter: alpha # (alpha: 알파벳 순으로 정렬, method: Http method 순으로 정렬)

---
spring:
  config:
    activate:
      on-profile: profile2
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: profile3
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(5IXRSND9vYt8oje4azSe+v7f56G99TmKo5Tt46CdnAQ4rCKfMftkaJWpscZ00jj4y7egK2rAtRJRyP8v1U6ekbsWsatlURZsH53s15UxWyUtv/MJTMKLW7phgFa1S0JT)
    username: ENC(tL/u2dsxQVNdHJS05MiCfw==)
    password: ENC(hAPUYou39PAqGj6UujBdr2qpNG4ynekB)
server:
  port: 80