spring:
  profiles:
    group:
      dev: profile1
      test: profile2

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
---
spring:
  config:
    activate:
      on-profile: profile1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${jdbcURL}
    username: ${jdbcUsername}
    password: ${jdbcPassword}

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
  packages-to-scan: com.jootcamp.superboard
  swagger-ui:
    display-request-duration: true # 딜레이를 두고 요청하도록 설정
    operations-sorter: alpha # (alpha: 알파벳 순으로 정렬, method: Http method 순으로 정렬)



---
spring:
  config:
    activate:
      on-profile: profile2
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

